server:
  port: 8088

spring:
  #  模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML
  #    数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
#    连接池设置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

mybatis:
  type-aliases-package: com.xike.blog.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.xike.blog.util.CommonMapper

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql